# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'w1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (
    QApplication,
    QMainWindow,
    QFrame,
    QFileDialog,
    QWidget,
)


class Ui_widget1(QWidget):
    def setupUi(self, widget1):
        widget1.setObjectName("widget1")
        widget1.resize(320, 240)
        self.comboBox = QtWidgets.QComboBox(widget1)
        self.comboBox.setGeometry(QtCore.QRect(10, 80, 87, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(widget1)
        self.lineEdit.setGeometry(QtCore.QRect(200, 80, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox_2 = QtWidgets.QComboBox(widget1)
        self.comboBox_2.setGeometry(QtCore.QRect(110, 80, 87, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.buttonBox = QtWidgets.QDialogButtonBox(widget1)
        self.buttonBox.setGeometry(QtCore.QRect(90, 170, 193, 28))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(widget1)
        QtCore.QMetaObject.connectSlotsByName(widget1)

    def retranslateUi(self, widget1):
        _translate = QtCore.QCoreApplication.translate
        widget1.setWindowTitle(_translate("widget1", "Form"))
        self.comboBox.setItemText(0, _translate("widget1", "X"))
        self.comboBox.setItemText(1, _translate("widget1", "Y"))
        self.comboBox_2.setItemText(0, _translate("widget1", ">"))
        self.comboBox_2.setItemText(1, _translate("widget1", "<"))
