# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PassThroughFilterUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PTFDialog(object):
    def setupUi(self, PTFDialog):
        PTFDialog.setObjectName("PTFDialog")
        PTFDialog.resize(320, 240)
        PTFDialog.setMinimumSize(QtCore.QSize(200, 100))
        PTFDialog.setMaximumSize(QtCore.QSize(500, 300))
        PTFDialog.setToolTip("")
        PTFDialog.setSizeGripEnabled(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(PTFDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.XYZcomboBox = QtWidgets.QComboBox(PTFDialog)
        self.XYZcomboBox.setObjectName("XYZcomboBox")
        self.XYZcomboBox.addItem("")
        self.XYZcomboBox.addItem("")
        self.XYZcomboBox.addItem("")
        self.horizontalLayout.addWidget(self.XYZcomboBox)
        self.logicalcomBox = QtWidgets.QComboBox(PTFDialog)
        self.logicalcomBox.setObjectName("logicalcomBox")
        self.logicalcomBox.addItem("")
        self.logicalcomBox.addItem("")
        self.logicalcomBox.addItem("")
        self.logicalcomBox.addItem("")
        self.logicalcomBox.addItem("")
        self.horizontalLayout.addWidget(self.logicalcomBox)
        self.lineEdit = QtWidgets.QLineEdit(PTFDialog)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.setBtn = QtWidgets.QPushButton(PTFDialog)
        self.setBtn.setObjectName("setBtn")
        self.horizontalLayout_2.addWidget(self.setBtn)
        self.clearBtn = QtWidgets.QPushButton(PTFDialog)
        self.clearBtn.setObjectName("clearBtn")
        self.horizontalLayout_2.addWidget(self.clearBtn)
        self.cancelBtn = QtWidgets.QPushButton(PTFDialog)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_2.addWidget(self.cancelBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(PTFDialog)
        QtCore.QMetaObject.connectSlotsByName(PTFDialog)

    def retranslateUi(self, PTFDialog):
        _translate = QtCore.QCoreApplication.translate
        PTFDialog.setWindowTitle(_translate("PTFDialog", "Dialog"))
        self.XYZcomboBox.setItemText(0, _translate("PTFDialog", "X"))
        self.XYZcomboBox.setItemText(1, _translate("PTFDialog", "Y"))
        self.XYZcomboBox.setItemText(2, _translate("PTFDialog", "Z"))
        self.logicalcomBox.setItemText(0, _translate("PTFDialog", ">="))
        self.logicalcomBox.setItemText(1, _translate("PTFDialog", ">"))
        self.logicalcomBox.setItemText(2, _translate("PTFDialog", "<"))
        self.logicalcomBox.setItemText(3, _translate("PTFDialog", "<="))
        self.logicalcomBox.setItemText(4, _translate("PTFDialog", "="))
        self.setBtn.setText(_translate("PTFDialog", "确定"))
        self.clearBtn.setText(_translate("PTFDialog", "清空"))
        self.cancelBtn.setText(_translate("PTFDialog", "退出"))
