# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1192, 863)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 981, 801))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1192, 28))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.treeView = QtWidgets.QTreeView(self.dockWidgetContents_2)
        self.treeView.setGeometry(QtCore.QRect(0, 0, 201, 821))
        self.treeView.setObjectName("treeView")
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)
        self.actionxin = QtWidgets.QAction(MainWindow)
        self.actionxin.setObjectName("actionxin")
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionGlobalRegist = QtWidgets.QAction(MainWindow)
        self.actionGlobalRegist.setObjectName("actionGlobalRegist")
        self.actionICP = QtWidgets.QAction(MainWindow)
        self.actionICP.setObjectName("actionICP")
        self.actionRPS = QtWidgets.QAction(MainWindow)
        self.actionRPS.setObjectName("actionRPS")
        self.actionzhitong = QtWidgets.QAction(MainWindow)
        self.actionzhitong.setObjectName("actionzhitong")
        self.actionCropHull = QtWidgets.QAction(MainWindow)
        self.actionCropHull.setObjectName("actionCropHull")
        self.actionopenStl = QtWidgets.QAction(MainWindow)
        self.actionopenStl.setObjectName("actionopenStl")
        self.actionClearDisplay = QtWidgets.QAction(MainWindow)
        self.actionClearDisplay.setObjectName("actionClearDisplay")
        self.actionColorBar = QtWidgets.QAction(MainWindow)
        self.actionColorBar.setObjectName("actionColorBar")
        self.menu.addAction(self.actionxin)
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.actionopenStl)
        self.menu_2.addAction(self.actionzhitong)
        self.menu_2.addAction(self.actionCropHull)
        self.menu_3.addAction(self.actionGlobalRegist)
        self.menu_3.addAction(self.actionICP)
        self.menu_3.addAction(self.actionRPS)
        self.menu_4.addAction(self.actionColorBar)
        self.menu_4.addAction(self.actionClearDisplay)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "滤波"))
        self.menu_3.setTitle(_translate("MainWindow", "对齐"))
        self.menu_4.setTitle(_translate("MainWindow", "显示"))
        self.actionxin.setText(_translate("MainWindow", "新建"))
        self.actionopen.setText(_translate("MainWindow", "读取点云"))
        self.actionGlobalRegist.setText(_translate("MainWindow", "粗配准"))
        self.actionICP.setText(_translate("MainWindow", "ICP"))
        self.actionRPS.setText(_translate("MainWindow", "手动选点"))
        self.actionzhitong.setText(_translate("MainWindow", "直通滤波"))
        self.actionCropHull.setText(_translate("MainWindow", "手动圈选"))
        self.actionopenStl.setText(_translate("MainWindow", "读取STL"))
        self.actionClearDisplay.setText(_translate("MainWindow", "清空"))
        self.actionColorBar.setText(_translate("MainWindow", "配准结果显示"))

